swagger: '2.0'
info:
  description: |
    Bus tracker API
  version: 1.0.0
  title: Bus Tracker API
  # put the contact info for your development or API team
  contact:
    email: dev@treq.me
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: api.treq.me:8080
basePath: /v1
schemes:
- http
# tags are used for organizing operations
tags:
- name: routes
  description: Routes ralated APIs
- name: buses
  description: Bus ralated APIs

paths:
  /buses/{busSystem}/{routeId}:
    get:
      tags:
      - buses
      summary: get buses
      operationId: getBus
      description: |
        Returns all bus objects given a route ID
      produces:
      - application/json
      parameters:
      - in: path
        name: busSystem
        description: Bus System. Now it support njt (NJ Transit) and nyw (NY Waterway)
        required: true
        type: string
      - in: path
        name: routeId
        description: Bus route ID
        required: true
        type: string
      responses:
        200:
          description: A collection of bus objects
          schema:
            type: array
            items:
              $ref: '#/definitions/Bus'
        404:
          description: Result not found due to invalid input
  /routes/{busSystem}:
    get:
      tags:
      - routes
      summary: get all active routes from all routes of a bus system
      operationId: getRoutes
      description: |
        Returns all active routes.
      produces:
      - application/json
      parameters:
      - in: path
        name: busSystem
        description: Bus System. Now it support njt (NJ Transit) and nyw (NY Waterway)
        required: true
        type: string
      responses:
        200:
          description: A single route object
          schema:
            type: array
            items:
              $ref: '#/definitions/BusRoute'
        404:
          description: Result not found due to invalid input
  /routes/{busSystem}/{routeId}:
    get:
      tags:
      - routes
      summary: get route by route ID
      operationId: getRouteById
      description: |
        Returns route by route ID
      produces:
      - application/json
      parameters:
      - in: path
        name: busSystem
        description: Bus System. Now it support njt (NJ Transit) and nyw (NY Waterway)
        required: true
        type: string
      - in: path
        name: routeId
        description: Bus route ID
        required: true
        type: string
      responses:
        200:
          description: A single route object
          schema:
            $ref: '#/definitions/BusRoute'
        404:
          description: Result not found due to invalid input
definitions:
  Bus:
    type: object
    required:
    - id
    - location
    - direction
    properties:
      id:
        type: string
        example: "1"
      location:
        $ref: '#/definitions/Location'
      direction:
        description: |
          Different bus system may use different direction systems. For now, NYW use integer where 0 means north, 90 means east etc. The value is always an incramental of 10 starting from 0. For NJT, it uses 16 Point Compass, where, for example, NNE is equivalant to 22.5
        type: string
        example: "NNS"
  Location:
    required:
    - longitude
    - latitude
    properties:
      longitude:
        type: number
        format: double
        example: 71.000000
      latitude:
        type: number
        format: double
        example: -41.654788
  BusRoute:
    required:
    - routeId
    - routeDescription
    - polylineArray
    properties:
      routeId:
        type: string
        example: "route1"
      routeDescription:
        type: string
        example: "34 st"
      polylineArray:
        type: array
        minItems: 0
        uniqueItems: true
        items:
          $ref: "#/definitions/Location"
      routeViewCenter:
        $ref: '#/definitions/Location'
      routeSpanLatitude:
        type: number
        format: double
        example: 71.000000
      routeSpanLongitude:
        type: number
        format: double
        example: -41.654788